### ISSUE TITLE
Should we add auto-rotation?

### ISSUE THREAD

**Issue by jonathandturner** [nushell/demo#29]
We use auto-rotation in the terminal to help fit things on the screen when it's a single long row. Feels like we might want to consider that for wasm-nu also:

![Screenshot from 2020-07-20 06-55-50](https://user-images.githubusercontent.com/547158/87882718-30073b80-ca56-11ea-909b-ff9a5bdd4be6.png)

Notice size of scrollbar.

**Comment by fdncred** [comment]
Please no. :) Help people learn that's what `pivot` is for.

**Comment by jzaefferer** [comment]
Maybe we can detect this case and suggest adding `| pivot` to the command?

**Comment by fdncred** [comment]
That sounds helpful - can we detect when the horizontal scrollbar is first enabled? If so, that may be an easy trigger to make that suggestion.
