### ISSUE TITLE
Readme button?

### ISSUE THREAD

**Issue by fdncred** [nushell/demo#41]
Was thinking that maybe there should be a readme button somewhere on the page that tells what's working and what's not working (i.e. @jzaefferer 's issue that lists it). Error handling is still in it's infancy and I don't want people trying it and getting aggravated and then assuming nushell as a whole doesn't support all the commands we claim it does.

**Comment by jzaefferer** [comment]
Good point. A line of text with a link would be a start (or enough), like "This is a work in progress. Not all commands work and some errors break everything, requiring a page reload. [More details on GitHub]"

**Comment by fdncred** [comment]
ya, that sounds good.
