### ISSUE TITLE
`ls` examples don't work in wasm

### ISSUE THREAD

**Issue by jonathandturner** [nushell/demo#42]
`ls *.foo` doesn't work in wasm. Doesn't look like we support any wildcards (yet?)

**Comment by jzaefferer** [comment]
I've looked into this - from what I understand, the globbed(?) path gets passed through to the `fs.readdirSync(path)` call (www/module.js:34), which doesn't support wildcards. At least https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback never mentions wildcards or globs, and that's what BrowserFS generally refers to.

Implementing the globbing by hand doesn't seem like a good idea. Using libraries like https://github.com/isaacs/node-glob#glob could work, if we can manage to load them in the wasm/extern context and make them work with BrowserFS.

Overall it doesn't quite seem worth the effort for the demo. Might be better to detect wilcards in lib/ls.rs and output an error, "glob/wildcard paths not supported in wasm".

**Comment by jonathandturner** [comment]
Thanks for looking. I'll close for now, since you're right it feels like something that's outside of "just a demo"
