### ISSUE TITLE
Loading indicator 

### ISSUE THREAD

**Issue by jzaefferer** [nushell/demo#43]
Loading the several MB of wasm and the zip file can take a while, and until then the demo shows up, but isn't usable. A simple loading indicator would help

Maybe via https://codepen.io/dsenneff/pen/jOWdvqx

**Comment by jonathandturner** [comment]
I wonder if there's a way to trim the wasm size down before we deploy

**Comment by jzaefferer** [comment]
The 1,5mb isn't too bad compared to the 15mb nu binary (on OSX)
