### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by jonathandturner** [nushell/demo#8]
Nu makes syntax highlighting available internally, so in theory we could expose this to wasm-nu, and then use the syntax highlighting information to color the user input.

So long as we don't interfere with them typing, it should be okay?

**Comment by jonathandturner** [comment]
This is some of the key logic:

https://github.com/nushell/nushell/blob/main/crates/nu-cli/src/shell/helper.rs#L114-L116

We could use a similar logic on the wasm-nu side to get the shapes (syntax shapes) for the line, and then we could do what we want after that.

**Comment by jzaefferer** [comment]
This sounds promising.

An alternative, or maybe a good combination, is https://codemirror.net/

**Comment by jzaefferer** [comment]
@jonathandturner I have no idea how to start here, and don't really feel like its worth the effort for the demo. Unless you want to put time into this, I suggest we close the ticket.

**Comment by jonathandturner** [comment]
Let's go ahead and close for now. We can get fancy when we feel like doing a "2.0"
